<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empleados [  
<!ELEMENT empleados (empleado*)>
    <!ATTLIST empleados total CDATA #REQUIRED>
<!ELEMENT empleado (nombre, apellidos)>
    <!ATTLIST empleado id ID #REQUIRED>
    <!ATTLIST empleado seccion (desarrollo | sistemas) "sistemas">
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
]>

<empleados total='2'>    
    <empleado id='e001' seccion="desarrollo">
        <nombre>Andres</nombre>
        <apellidos>Lopez Navarro</apellidos>
    </empleado>
    <empleado id='e002'>
        <nombre>Maria</nombre>
        <apellidos>Suarez Pelaez</apellidos>
    </empleado>
</empleados>